package edu.uci.ics.hyracks.imru.example.helloworld;

import java.io.Serializable;

/**
 * Object which is generated by map(), aggregated in reduce() and used in
 * update()
 */
public class HelloWorldIncrementalResult implements Serializable {
    public int length;
}
