package edu.uci.ics.hyracks.imru.example.kmeans;

import java.io.Serializable;

/**
 * Object which is generated by map(), aggregated in reduce() and used in
 * update()
 */
public class KMeansCentroids implements Serializable {
    Centroid[] centroids;

    public KMeansCentroids(int k) {
        centroids = new Centroid[k];
        for (int i = 0; i < k; i++)
            centroids[i] = new Centroid();
    }
}
